---
AWSTemplateFormatVersion: 2010-09-09

Description: CDN and S3 bucket for website

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
    - test
    - dev
    - prod

  CNAME:
    Type: CommaDelimitedList
    Default: "giarevn.net, www.giarevn.net, *.giarevn.net"

  SSLCertificateArn:
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'giare-${Environment}-frontend'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CDNLogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'giare-${Environment}-cdn-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ReadPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3Bucket

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases: !Ref CNAME
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificateArn
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          DefaultTTL: 300 # deprecated use cache policy
          ForwardedValues: # deprecated
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # deprecated
          MinTTL: 60 # deprecated
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt 'S3Bucket.RegionalDomainName'
          Id: s3origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        PriceClass: 'PriceClass_200'
        CustomErrorResponses:
        - ErrorCachingMinTTL: 10
          ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        Logging:
          Bucket: !GetAtt 'S3Bucket.RegionalDomainName'
          Prefix: cdn
