---
version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Run YAML linting
        command: make lint
    - run:
        name: Validate Cloudformation templates
        command: make validate

  deployInfra:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Deploy CDN
        command: make deployInfra

  deployApp:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Install Node and NPM
        command: |
          sudo apt-get -y install curl
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get -y install nodejs
          sudo apt-get -y install npm
          node --version
          npm --version
    - run:
        name: Run build
        command: npm run build
    # - run:
    #     name: Deploy to S3
    #     command: 

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - deployApp
    # - test
    # - deployInfra:
    #     filters:
    #       branches:
    #         only: main
    #       tags:
    #         ignore: /.*/
