---
version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Run YAML linting
        command: make lint
    - run:
        name: Validate Cloudformation templates
        command: make validate

  deployInfra:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Deploy CDN
        command: make deployInfra

  deployApp:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Check Node and NPM
        command: |
          node --version
          npm --version
    - run:
        name: Run build
        command: | 
          npm install
          CI=false npm run build
    - run:
        name: Deploy to S3
        command: make deployApp

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - test
    - deployInfra:
        requires:
        - test
        filters:
          branches:
            only: main
          tags:
            ignore: /.*/
    - deployApp:
        requires:
        - deployInfra
        filters:
          branches:
            only: main
          tags:
            ignore: /.*/
